[defaults]
name = "default runner"
cmd = "echo 'default runner set'"
quit_fast = false

[[runners]]
name = "haskell"
cmd = "ghci"
quit_fast = true

[[runners]]
name = "rust (release)"
cmd = "cargo run --release"
quit_fast = false

[[runners]]
name = "rust"
cmd = "cargo run"
quit_fast = false

[[runners]]
name = "dotter deploy"
cmd = "dotter -v"
quit_fast = false

[[runners]]
name = "graphviz dot"
cmd = "dot {file} -Tsvg | feh --scale-down --geometry '900x900' -"
quit_fast = true

[[runners]]
name = "mermaid diagram"
cmd = "[[ {file}.mmd -nt {file}.png ]] && mmdc -i {file}.mmd -o {file}.png -t neutral; feh {file}.png"
quit_fast = true

[[runners]]
name = "python"
cmd = "python {file}"
quit_fast = false

[[runners]]
name = "python (interactive)"
cmd = "python -i {file}"
quit_fast = true

[[runners]]
name = "rust test"
cmd = "cargo test"
quit_fast = false

[[runners]]
name = "rust with args"
cmd = "cargo run -- {args}"
quit_fast = false

[[runners]]
name = "rust build"
cmd = "cargo build"
quit_fast = false

[[runners]]
name = "C build"
cmd = "make {rule}"
quit_fast = false

[[runners]]
name = "C build & run (fast exit)"
cmd = "make run"
quit_fast = true

[[runners]]
name = "C build & run"
cmd = "make run"
quit_fast = false

[[runners]]
name = "unique"
cmd = "{command}"
quit_fast = false
