[defaults]
name = "default runner"
cmd = "echo 'default runner set'"
quit_fast = false

[[runners]]
name = "haskell"
cmd = "ghci"
quit_fast = true

[[runners]]
name = "rust run"
cmd = "cargo run"
quit_fast = false

[[runners]]
name = "echo test"
cmd = "echo {thing}"
quit_fast = false

[[runners]]
name = "dotter deploy"
cmd = "dotter -v"
quit_fast = false

[[runners]]
name = "rust test"
cmd = "cargo test"
quit_fast = false

[[runners]]
name = "rust test & run"
cmd = "cargo run; cargo test"
quit_fast = false

[[runners]]
name = "unique"
cmd = "{command}"
quit_fast = false
