#!/bin/bash


if ! bw login --check &> /dev/null ; then
    if [ -f ~/.secrets/bw_clientid ]; then
        BW_CLIENTID=$(cat ~/.secrets/bw_clientid)
    else
        echo "cannot get bw_clientid, does not exist"
    fi

    if [ -f ~/.secrets/bw_clientsecret ]; then
        BW_CLIENTSECRET=$(cat ~/.secrets/bw_clientsecret)
    else
        echo "cannot get bw_clientsecret, does not exist"
    fi
    echo "not yet logged in"
    bw login --apikey
    unset BW_CLIENTID
    unset BW_CLIENTSECRET
fi


if ! bw unlock --check &> /dev/null ; then
    echo "vault locked"
    session_key=$(bw unlock --raw)
    echo "new session key: $session_key"
    echo "$session_key" > ~/.secrets/bw_session
    unset BW_SESSION
    export BW_SESSION=$session_key
fi

