#!/bin/bash

mkdir -p ~/proj
mkdir -p ~/uni

uni_proj=$(ls -l --color=no ~/uni | awk '/^d/ {print "uni/"$9}')
personal_proj=$(ls -l --color=no ~/proj | awk '/^d/ {print "proj/"$9}')

projects=$(printf "%s\n" "$personal_proj" "$uni_proj")
projects=$(printf "%s\ndotfiles\n" "$projects")

chosen=$(echo "$projects" | fzf)

if [[ "$chosen" == "dotfiles" ]]; then
    printf "%s" "$HOME/.dotfiles"
else
    printf "%s" "$HOME/$chosen"
fi
