#!/bin/bash
#
# Supported unison version (must match server)
# unison version 2.53.2 (ocaml 4.14.1)

unison -batch -prefer newer -copyonconflict -silent -sshargs "-i ~/.ssh/unison_key" -repeat watch ~/sync/ 'ssh://unison/sync'
