#!/bin/bash

systemctl --user status unison-wrapper &> /dev/null

stat=$?

size=$(du -sbh sync/ | awk '{print $1}')

case $stat in
    0)
        echo "OK $size"
        ;;
    1 | 2 | 4)
        echo "ERR $size"
        ;;
    3)
        echo "STP $size"
        ;;
    *)
        echo "UKN $size"
        ;;
esac
