#!/bin/bash

echo "work mode starting"

echo "1" > ~/work/.work-mode

if sshpass -f/home/anna/.secrets/ssh-gateway ssh -q -S ~/work/.socks/tunnel -O check work > /dev/null; then
    echo "tunnel to webproxy already established"
else
    sshpass -f/home/anna/.secrets/ssh-gateway ssh -fN -M -S ~/work/.socks/tunnel work > /dev/null
    echo "new tunnel to webproxy established on port 3128"
fi

keychain ~/.ssh/id_ed25519

# start some programs

slack &> /dev/null &
disown $!

thunderbird &> /dev/null &
disown $!
