#!/bin/bash


if [[ -z $1 ]]; then
    echo "pass an ssh target please"
    exit 1
fi

# cat ~/docs/gateway | xclip -i -selection clipboard -r
# ssh -A $1

if [[  "$1" == "itadmin"  ||  "$1" == "root@itadmin"  ]]; then
    /bin/ssh $@
    exit 0
fi

if [[ `cat ~/work/.work-mode` == "1" ]]; then
    sshpass -f/home/anna/docs/gateway ssh $@
else
    /sbin/ssh $@
fi
