#!/bin/bash

echo "exiting work mode"
echo "0" > ~/work/.work-mode


if ssh -S ~/.socks/webproxy -O check gateway &> /dev/null; then
    ssh -S ~/.socks/webproxy -O exit gateway > /dev/null
else
    echo "no tunnel to webproxy exists, skipping"
fi



if ssh -S ~/.socks/glproxy -O check gateway &> /dev/null; then
    ssh -S ~/.socks/glproxy -O exit gateway > /dev/null
else
    echo "no tunnel to gitlab exists, skipping"
fi

echo "ending sshfs"
umount ~/work/vm
umount ~/work/kp-mnt
