#!/bin/bash

echo "exiting work mode"
echo "0" > ~/work/.work-mode


if ssh -S ~/work/.socks/tunnel -O check work &> /dev/null; then
    ssh -S ~/work/.socks/tunnel -O exit work > /dev/null
else
    echo "no tunnel to webproxy exists, skipping"
fi

echo "ending sshfs"
umount ~/work/vm
umount ~/work/kp-mnt

pkill slack
