[helpers]

[default]
depends = []

[default.files]
i3 = "~/.config/i3"
polybar = "~/.config/polybar"
kitty = "~/.config/kitty"
rofi = "~/.config/rofi"
".Xmodmap" = "~/.Xmodmap"
".Xresources" = "~/.Xresources"
fish = "~/.config/fish"
nvim = "~/.config/nvim"
".util" = "~/.util"
"tmux/.tmux.conf" = "~/.tmux.conf"
"git/config" = "~/.gitconfig"
git = "~/.config/git"
gitui = "~/.config/gitui"
"redshift/redshift.conf" = "~/.config/redshift.conf"
i3lock = "~/.config/i3lock"
sshconfig = "~/.ssh/config"
work = "~/work"
runfast = "~/.config/runfast"
opt = "~/opt"
".bashrc" = "~/.bashrc"
"picom.conf" = "~/.config/picom.conf"
# "cheat.bash" = "~/opt/cheat.bash"
kermit-term = "~/.config/kermit.conf"
xscreensaver = "~/.xscreensaver"

[default.variables]

[desktop]
depends = []

[desktop.variables]
wm_font_size = 10
polybar_icon_font_size = 14
polybar_icon_offset = 2
i3lock_cmd = "i3lock -ti ~/.config/i3lock/lock-fullscreen.png"
polybar_height = 19
polybar_right_modules = "upd-end-sep updates vol-upd-sep pulseaudio date-vol-sep date"
term_font_size = 10.0
polybar_offset = 2
xscreensaver_mode="random"

[thinkpad]
depends = []

[thinkpad.variables]
wm_font_size = 10
polybar_icon_font_size = 16
polybar_icon_offset = 3
i3lock_cmd = "i3lock -ti ~/.config/i3lock/lock-fullscreen.png"
polybar_height = 19
polybar_right_modules = "upd-end-sep updates vol-upd-sep pulseaudio bat-vol-sep bat_internal bat_swap date-bat-sep date"
term_font_size = 12.0
polybar_offset = 2
xscreensaver_mode="blank"
