[helpers]

[default]
depends = []

[default.files]
i3 = "~/.config/i3"
polybar = "~/.config/polybar"
rofi = "~/.config/rofi"
".Xresources" = "~/.Xresources"
nvim = "~/.config/nvim"
".util" = "~/.util"
"tmux/.tmux.conf" = "~/.tmux.conf"
"git/config" = "~/.gitconfig"
"git/config.work" = "~/.gitconfig.work"
git = "~/.config/git"
gitui = "~/.config/gitui"
"redshift/redshift.conf" = "~/.config/redshift.conf"
sshconfig = "~/.ssh/config"
runfast = "~/.config/runfast"
opt = "~/opt"
".bashrc" = "~/.bashrc"
"picom.conf" = "~/.config/picom.conf"
xscreensaver = "~/.xscreensaver"
dunst = "~/.config/dunst"
"systemd/user" = "~/.config/systemd/user/"
"kitty.conf" = "~/.config/kitty/kitty.conf"

[default.variables]

[cynthia]
depends = []

[cynthia.variables]
wm_font_size = 16
polybar_icon_font_size = 14
polybar_icon_offset = 2
i3lock_cmd = "i3lock -ti ~/.config/i3lock/lock-fullscreen.png"
polybar_height = 26
polybar_right_modules = "unison updates pulseaudio memory cpu date tray"
term_font_size = 10.0
polybar_offset = 2
xscreensaver_mode="random"
wallpaper_cmd="nitrogen --restore"
dunst_scale = 2

[thinkpad]
depends = []

[thinkpad.variables]
wm_font_size = 10
polybar_icon_font_size = 16
polybar_icon_offset = 3
i3lock_cmd = "i3lock -ti ~/.config/i3lock/lock-fullscreen.png"
polybar_height = 19
polybar_right_modules = "bat_internal bat_swap unison updates pulseaudio memory cpu date tray"
term_font_size = 8.0
polybar_offset = 2
xscreensaver_mode="random"
wallpaper_cmd="~/.fehbg"
dunst_scale = 0

[thinkpad.files]
".Xmodmap" = "~/.Xmodmap"
".fehbg" = "~/.fehbg"
