[helpers]

[default]
depends = []

[default.files]
i3 = "~/.config/i3"
polybar = "~/.config/polybar"
kitty = "~/.config/kitty"
rofi = "~/.config/rofi"
".Xmodmap" = "~/.Xmodmap"
fish = "~/.config/fish"
".emacs.d/init.el" = "~/.emacs.d/init.el"
".emacs.d/anna-conf.org" = "~/.emacs.d/anna-conf.org"
nvim = "~/.config/nvim"
".util" = "~/.util"
"tmux/.tmux.conf" = "~/.tmux.conf"
git = "~/.config/git"

[default.variables]

[desktop]
depends = []

[desktop.variables]
wm_font_size = 10
i3lock_cmd = "i3lock-fancy-dualmonitor -g"
polybar_height = 19
polybar_right_modules = "pomo-end-sep polypomo upd-pomo-sep updates vol-upd-sep pulseaudio date-vol-sep date"
term_font_size = 18.0
polybar_offset = 2

[thinkpad]
depends = []

[thinkpad.variables]
wm_font_size = 10
i3lock_cmd = "i3lock-fancy"
polybar_height = 19
polybar_right_modules = "upd-end-sep updates vol-upd-sep pulseaudio bat-vol-sep bat_internal bat_swap date-bat-sep date"
term_font_size = 18.0
polybar_offset = 2
