#+title Anna's Emacs Config (Org-Mode)
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el
* Init Settings
** Start in my TODO orgmode file
#+begin_src emacs-lisp
  (setq initial-buffer-choice "~/Dropbox/notes/todo.org")
#+end_src
* Package System Setups
** Package Repos
#+begin_src emacs-lisp
  (require 'package)
  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")
                           ("elpa" . "https://elpa.gnu.org/packages/")))
  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))
#+end_src

** Use-package setup
#+begin_src emacs-lisp
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))
  (require 'use-package)
  (setq use-package-always-ensure 't)
#+end_src
   
* General Settings
** Ivy
#+begin_src emacs-lisp
  (use-package ivy
    :diminish
    :bind (("C-s" . swiper)
           :map ivy-minibuffer-map
           ("TAB" . ivy-alt-done)
           ("C-l" . ivy-alt-done)
           ("C-j" . ivy-next-line)
           ("C-h" . ivy-previous-line)
           :map ivy-switch-buffer-map
           ("C-k" . ivy-previous-line)
           ("C-l" . ivy-done)
           ("C-d" . ivy-switch-buffer-kill)
           :map ivy-reverse-i-search-map
           ("C-k" . ivy-previous-line)
           ("C-d" . ivy-reverse-i-search-kill))
    :config
    (ivy-mode 1))

  (use-package ivy-rich
    :init
    (ivy-rich-mode 1))
#+end_src

   provides better completion in things like M-x
  
** Counsel
#+begin_src emacs-lisp
  (use-package counsel
    :bind (("M-x" . counsel-M-x)
           ("C-x C-f" . counsel-find-file)
           :map minibuffer-local-map
           ("C-r" . counsel-minibuffer-history)))
#+end_src

   provides better versions of find-file and M-x
   
** Swiper
#+begin_src emacs-lisp
  (use-package swiper)
#+end_src

   provides a great fuzzy search in files (C-s)

** Which-key
#+begin_src emacs-lisp
  (use-package which-key
    :init (which-key-mode)
    :diminish which-key-mode
    :config
    (setq which-key-idle-delay 0.3))
#+end_src

   displays possible keybinds after another keybind is pressed
   
** Helpful
#+begin_src emacs-lisp
  (use-package helpful
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . counsel-describe-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key))
#+end_src

   provides better formatted help pages

** Put autosaves in the cache, not project dirs
#+begin_src emacs-lisp
    (setq user-emacs-directory "~/.cache/emacs")
    (use-package no-littering)
    (setq auto-save-file-name-transforms
          `((".*", (no-littering-expand-var-file-name "auto-save/") t)))
#+end_src
** Dired
*** keep only one dired buffer at a time
#+begin_src emacs-lisp
  (setq dired-kill-when-opening-new-dired-buffer t)
#+end_src
* UI
** Basic UI
*** Disable Bad UI Features
#+begin_src emacs-lisp
  (setq inhibit-startup-message t)
  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
  (setq visible-bell t)
  (set-fringe-mode 10)
#+end_src
  
*** Font Settings
#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist '(font . "NotoSansMono"))
  (set-face-attribute 'default nil :font "NotoSansMono" :height 130)
#+end_src 

the 1st line is to fix emacs setting the incorrect font in daemon mode

*** Theme
#+begin_src emacs-lisp
    (use-package doom-themes
      :ensure t
      :config
      (setq doom-themes-enable-bold t
            doom-themes-enable-italic t)
      (load-theme 'doom-snazzy t)
      (doom-themes-visual-bell-config))
#+end_src

   
*** Modeline
#+begin_src emacs-lisp
  (use-package doom-modeline
    :ensure t
    :init (doom-modeline-mode 1))
  (setq doom-modeline-height 16)
  (setq doom-modeline-modal-icon nil)

  (use-package all-the-icons)
#+end_src
all-the-icons is brought in here because doom-modeline requries it to display language
icons properly

** Programming Specific UI
  Contains UI Options Specific To Programming

*** Line / Column Numbers
#+begin_src emacs-lisp
  (column-number-mode)
  (global-display-line-numbers-mode t)

  ;; disable line nums for some modes
  (dolist (mode '(org-mode-hook
                  shell-mode-hook
                  term-mode-hook
                  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))
#+end_src

*** Rainbow Delimiters
#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))
#+end_src

* Org-Mode Config
** Auto Tangle on Save
#+begin_src emacs-lisp
  (defun as/org-babel-tangle-config ()
    (when (or
(string-equal (buffer-file-name) (expand-file-name "~/.dotfiles/.emacs.d/anna-conf.org"))
(string-equal (buffer-file-name) (expand-file-name "~/.dotfiles/systemconf.org")))
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle))))
  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'as/org-babel-tangle-config)))
#+end_src

this code block automatically tangles all code blocks
note: this code does not like symlinks.

** Reload inline images on eval
#+begin_src emacs-lisp
  (add-hook 'org-babel-after-execute-hook 'org-redisplay-inline-images)
#+end_src

** Define Org-Mode Specific Settings
#+begin_src emacs-lisp
    (defun as/org-mode-setup ()
      (org-indent-mode)
      (visual-line-mode 0)
      (setq org-src-preserve-indentation t))
#+end_src
  
** Require Org-Mode
#+begin_src emacs-lisp
  (use-package org
    :hook (org-mode . as/org-mode-setup)
    :config
    (setq org-ellipsis "▼"))
#+end_src

** Configure Babel Languages
#+begin_src emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (python . t)
     (C . t)
     (plantuml . t)
     (latex . t)
     (jupyter . t)))
  (setq org-confirm-babel-evaluate nil)
#+end_src

** Set Templates
#+begin_src emacs-lisp
  (require 'org-tempo)
  (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("cl" . "src c"))
  (add-to-list 'org-structure-template-alist '("py" . "src python"))
#+end_src

** Org-Superstar
#+begin_src emacs-lisp
  ;;(use-package org-superstar)
  ;;(add-hook 'org-mode-hook (lambda () (org-superstar-mode 1)))
#+end_src

org-superstar currently causes issues with fontifying ANSI colour code output in org mode, so it will remain disabled until that is fixed

* Key-Binding
** General
#+begin_src emacs-lisp
  (use-package general
    :config
    (general-create-definer as/leader-keys
      :keymaps '(normal insert visual emacs)
      :prefix "SPC"
      :global-prefix "C-SPC")
    (as/leader-keys
      "t" '(:ignore t :which-key "toggles")
      "o" '(:ignore t :which-key "org-mode")))

  (as/leader-keys
    "oi" '(org-indent-block :which-key "indent org mode block")
    "tw" '(whitespace-mode :which-key "toggle whitespace"))
#+end_src

   General provides a global user prefix (C-SPC) which works as a 'leader-key' for assigning
   personally important functions / workflow related stuff

   #+begin_src emacs-lisp
(general-define-key
 "C-M-j" 'counsel-switch-buffer
 "<escape>" 'keyboard-escape-quit)
   #+end_src

   also provides an easier way of defining global keybinds

** Hydra
#+begin_src emacs-lisp
  (use-package hydra)

  (defhydra hydra-text-scale (:timeout 4)
    "scale text"
    ("j" text-scale-increase "in")
    ("k" text-scale-decrease "out")
    ("f" nil "finished" :exit t))

  (as/leader-keys
    "ts" '(hydra-text-scale/body :which-key "scale text"))
#+end_src 

   hydra provides an interface for commands which often need to be run successively,
   for instance increase / decrease the text scale.
   Uses the leader-keys mapping which i defined in the General keybinds section

** Evil Mode

*** Add extra modes to use evil mode
#+begin_src emacs-lisp
  (defun as/evil-hook ()
    (dolist (mode '(custom-mode
                    eshell-mode
                    git-rebase-mode
                    sauron-mode
                    term-mode))
      (add-to-list 'evil-emacs-state-modes mode)))
#+end_src

*** Install & Activate evil mode
#+begin_src emacs-lisp
  (use-package evil
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    :config
    (evil-mode 1)
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)
    (evil-define-key 'normal 'local "K" 'man)
    (evil-define-key 'visual 'local "C-x C-;" 'comment-or-uncomment-region)
    (evil-set-initial-state 'messages-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal))
#+end_src
  
*** Install & Activate evil collection
#+begin_src emacs-lisp
  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))
#+end_src

evil collection is a package which adds bindings for other common non-text editor
modes.

*** Add undo-fu

#+begin_src emacs-lisp
  (use-package undo-fu)
#+end_src

* Development
** Enable Automatic 2nd Bracket Insertion
#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook 'electric-pair-mode t)
#+end_src

** Turn on relative line numbers
#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
#+end_src
 
** Projectile
#+begin_src emacs-lisp
  (use-package projectile
    :diminish projectile-mode
    :config (projectile-mode)
    :custom((projectile-completion-system 'ivy))
    :bind-keymap ("C-c p" . projectile-command-map)
    :init
    (when (file-directory-p "~/proj")
      (setq projectile-project-search-path '("~/proj"))))

    (use-package counsel-projectile
      :after projectile
      :config (counsel-projectile-mode))
#+end_src
** Magit (Git Integration)

#+begin_src emacs-lisp
  (use-package magit)
#+end_src

   magit is git integration for emacs

** LSP-Mode
#+begin_src emacs-lisp
  (use-package lsp-mode
    :commands (lsp lsp-deferred)
    :init
    (setq lsp-keymap-prefix "C-c l")
    :config
    (lsp-enable-which-key-integration t))

#+end_src

*** UI Improvements
#+begin_src emacs-lisp
    (use-package lsp-ui
      :hook (lsp-mode . lsp-ui-mode)
      :custom
      (lsp-ui-doc-position 'bottom)
      (lsp-ui-doc-max-height 5)
      (lsp-signature-doc-lines 5))
#+end_src

*** LSP-Ivy
#+begin_src emacs-lisp
  (use-package lsp-ivy)
#+end_src

*** Company Mode Integration
#+begin_src emacs-lisp
  (use-package company
    :after lsp-mode
    :hook (lsp-mode . company-mode)
    :bind (:map company-active-map
                ("<tab>" . company-complete-selection))
    (:map lsp-mode-map
          ("<tab>" . company-indent-or-complete-common))
    :custom
    (company-minimum-prefix-length 1)
    (company-idle-delay 0.0))

  (use-package company-box
    :hook (company-mode . company-box-mode))
#+end_src

** Flycheck
#+begin_src emacs-lisp
  (use-package flycheck
    :ensure t
    :init (global-flycheck-mode))
  (define-key flycheck-mode-map flycheck-keymap-prefix nil)
  (setq flycheck-keymap-prefix (kbd "C-c s"))
  (define-key flycheck-mode-map flycheck-keymap-prefix flycheck-command-map)
#+end_src

this enables syntax highlighting, the key to check is C-c s

** Tree-Sitter
#+begin_src emacs-lisp
  (use-package tree-sitter)
  (use-package tree-sitter-langs)
  (global-tree-sitter-mode)
  (add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode)
#+end_src

#+RESULTS:
** Enable company-mode in prog-mode
#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook 'company-mode t) 
#+end_src
** Enable origami-mode in prog-mode
#+begin_src emacs-lisp
  (use-package origami)
  (add-hook 'prog-mode-hook 'origami-mode t) 
#+end_src
** fix tab fuckery with SmartTabs
#+begin_src emacs-lisp
   ;(setq-default indent-tabs-mode nil)
   ;(use-package smart-tabs-mode)
   ;(smart-tabs-insinuate 'c 'java)
   (setq-default c-basic-offset 4)
   (setq-default tab-width 4)
#+end_src

** YASnippet

#+begin_src emacs-lisp
  (use-package yasnippet)
#+end_src

YASnippet is a plugin to allow insertion of snippets into code
 
** Language Specific Configs
*** C
**** set my own init hook for c to fix some things
#+begin_src emacs-lisp
(defun as/c-init-hook ()
  ;;(define-key c-mode-base-map "\C-c" 'c-context-line-break)
  (setq tab-width 4 indent-tabs-mode nil)
  (electric-pair-mode t) ;;turn on auto pair brackets
  (setq backward-delete-char-untabify-method 'hungry) ;; delete tabs at once
  ;(hs-minor-mode) ;; turn on folding support (z a to toggle)
  )
(add-hook 'c-initialization-hook 'as/c-init-hook)
#+end_src
**** c-headers completion
#+begin_src emacs-lisp
  (use-package company-c-headers)
  (add-to-list 'company-backends 'company-c-headers)
#+end_src

**** each buffer required commands
#+begin_src emacs-lisp
(defun as/c-buffer-init ()
  (lsp)
  (yas-minor-mode))

  (add-hook 'c-mode-hook 'as/c-buffer-init)
#+end_src

some commands need running on each buffer open for C mode.

**** fix indentation style
#+begin_src emacs-lisp
  (setq c-default-style "linux"
        c-basic-offset 4)
#+end_src

**** manpage keybind

#+begin_src emacs-lisp

#+end_src

set `K` (in normal mode) to run the command `man`

**** note on build -> run
we can use C-c p P to do a test command such as:
`cd d14 && make oneT && ./a.out`
this will rememeber the previous command

we can also use C-c p u to do a run command such as:
`cd d14 && make one && ./a.out`
this will also remember the previous command

*** Makefile
#+begin_src emacs-lisp
  (defun as/makefile-init-hook ()
  (setq tab-width 4))

  (add-hook 'makefile-gmake-mode-hook 'as/makefile-init-hook)
#+end_src

*** Haskell
**** Install haskell-mode
#+begin_src emacs-lisp
  (use-package haskell-mode)
#+end_src
*** Java
**** LSP-Mode
#+begin_src emacs-lisp
  (use-package lsp-java)
  (add-hook 'java-mode-hook 'lsp)
#+end_src

*** Python
**** Python Mode
#+begin_src emacs-lisp
  (use-package python-mode
    :ensure t
    :hook (python-mode . lsp-deferred))
#+end_src

**** LSP
#+begin_src emacs-lisp
  (add-hook 'python-mode-hook 'lsp)
  (use-package lsp-jedi
  :ensure t
  :config
  (with-eval-after-load "lsp-mode"
    (add-to-list 'lsp-disabled-clients 'pyls)))
#+end_src

**** Org Mode as Jupyter Notebook
#+begin_src emacs-lisp
  (use-package jupyter)
#+end_src
***** Fix ANSI colour codes
#+begin_src emacs-lisp
(defun display-ansi-colors ()
  (ansi-color-apply-on-region (point-min) (point-max)))

(add-hook 'org-babel-after-execute-hook #'display-ansi-colors)
#+end_src

*** Vimrc
#+begin_src emacs-lisp
  (use-package vimrc-mode)
#+end_src

*** Fish Scripting
#+begin_src emacs-lisp
  (use-package fish-mode)
  (use-package fish-completion)
#+end_src
 
